# Generated by Django 2.1.3 on 2019-02-18 10:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuizName', models.CharField(max_length=250)),
                ('QuizCreator', models.CharField(max_length=250)),
                ('Date', models.CharField(default=datetime.datetime(2019, 2, 18, 10, 3, 43, 613238, tzinfo=utc), max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='QuizEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=250)),
                ('AlternativeA', models.CharField(max_length=250)),
                ('AlternativeB', models.CharField(max_length=250)),
                ('AlternativeC', models.CharField(max_length=250)),
                ('Correct', models.CharField(max_length=250)),
                ('QuizID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Quiz')),
            ],
        ),
    ]
