# Generated by Django 2.1.3 on 2019-02-18 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Date',
            field=models.CharField(default=datetime.datetime(2019, 2, 18, 11, 36, 53, 204113, tzinfo=utc), max_length=250),
        ),
    ]
