# Generated by Django 2.1.3 on 2019-04-04 11:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(max_length=250, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(default=datetime.datetime(2019, 4, 4, 11, 16, 37, 788974, tzinfo=utc), max_length=100)),
                ('description', models.CharField(max_length=4000)),
                ('shortDescription', models.CharField(default='A description', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.AutoField(max_length=250, primary_key=True, serialize=False)),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Article')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('file', models.FileField(default='UNDEFINED', unique=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='QuizLink',
            fields=[
                ('id', models.AutoField(max_length=250, primary_key=True, serialize=False)),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Article')),
            ],
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='QuizCreator',
            new_name='quizCreator',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='QuizName',
            new_name='quizName',
        ),
        migrations.RenameField(
            model_name='quizentry',
            old_name='AlternativeA',
            new_name='alternativeA',
        ),
        migrations.RenameField(
            model_name='quizentry',
            old_name='AlternativeB',
            new_name='alternativeB',
        ),
        migrations.RenameField(
            model_name='quizentry',
            old_name='AlternativeC',
            new_name='alternativeC',
        ),
        migrations.RenameField(
            model_name='quizentry',
            old_name='Correct',
            new_name='correct',
        ),
        migrations.RenameField(
            model_name='quizentry',
            old_name='Question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='quizentry',
            old_name='QuizID',
            new_name='quizID',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='Date',
        ),
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 4, 4, 11, 16, 37, 786973, tzinfo=utc), max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.AutoField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='quizlink',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Quiz'),
        ),
        migrations.AddField(
            model_name='articlelink',
            name='filePath',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.File', to_field='file'),
        ),
    ]
