# Generated by Django 2.1.3 on 2019-02-26 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20190226_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Description',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 2, 26, 14, 37, 50, 333005, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 2, 26, 14, 37, 50, 329007, tzinfo=utc), max_length=100),
        ),
    ]
