# Generated by Django 2.1.3 on 2019-04-04 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20190404_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='shortDescription',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='articlelink',
            old_name='filePath',
            new_name='filepath',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quizCreator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quizName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quizentry',
            old_name='alternativeA',
            new_name='alta',
        ),
        migrations.RenameField(
            model_name='quizentry',
            old_name='alternativeB',
            new_name='altb',
        ),
        migrations.RenameField(
            model_name='quizentry',
            old_name='alternativeC',
            new_name='altc',
        ),
        migrations.RenameField(
            model_name='quizentry',
            old_name='quizID',
            new_name='quiz',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 4, 4, 12, 34, 41, 65608, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 4, 4, 12, 34, 41, 64608, tzinfo=utc), max_length=100),
        ),
    ]
