# Generated by Django 2.1.3 on 2019-03-04 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20190226_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 3, 4, 10, 15, 22, 912990, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 3, 4, 10, 15, 22, 910992, tzinfo=utc), max_length=100),
        ),
    ]
