# Generated by Django 2.1.3 on 2019-04-10 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20190404_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creator',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='file',
            name='creator',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 4, 10, 7, 14, 52, 432610, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 4, 10, 7, 14, 52, 416986, tzinfo=utc), max_length=100),
        ),
    ]
