# Generated by Django 2.1.3 on 2019-02-18 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20190218_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filepath',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='UNDEFINED', upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Date',
            field=models.CharField(default=datetime.datetime(2019, 2, 18, 13, 42, 23, 995313, tzinfo=utc), max_length=250),
        ),
    ]
