# Generated by Django 2.1.3 on 2019-04-10 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20190410_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescore',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 4, 10, 8, 44, 54, 740493, tzinfo=utc), max_length=100),
        ),
        migrations.AddField(
            model_name='articlescore',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 4, 10, 8, 44, 54, 740493, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 4, 10, 8, 44, 54, 740493, tzinfo=utc), max_length=100),
        ),
    ]
