# Generated by Django 2.1.3 on 2019-03-04 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20190304_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='shortDescription',
            field=models.CharField(default='A description', max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 3, 4, 13, 46, 10, 725682, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 3, 4, 13, 46, 10, 725682, tzinfo=utc), max_length=100),
        ),
    ]
