# Generated by Django 2.1.3 on 2019-02-18 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20190218_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Date',
            field=models.CharField(default=datetime.datetime(2019, 2, 18, 13, 53, 14, 211472, tzinfo=utc), max_length=250),
        ),
    ]
