# Generated by Django 2.1.3 on 2019-02-19 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20190218_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Date',
            field=models.CharField(default=datetime.datetime(2019, 2, 19, 12, 37, 10, 386478, tzinfo=utc), max_length=250),
        ),
    ]
