# Generated by Django 2.1.3 on 2019-04-10 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20190410_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescore',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 4, 10, 10, 1, 2, 316349, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='articlescore',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 4, 10, 10, 1, 2, 316349, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 4, 10, 10, 1, 2, 308829, tzinfo=utc), max_length=100),
        ),
    ]
