# Generated by Django 2.1.3 on 2019-03-05 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20190304_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 3, 5, 7, 23, 29, 222579, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 3, 5, 7, 23, 29, 221578, tzinfo=utc), max_length=100),
        ),
    ]
