# Generated by Django 2.1.3 on 2019-04-10 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20190410_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AlterField(
            model_name='articlescore',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
