# Generated by Django 2.1.3 on 2019-02-25 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20190219_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(max_length=250, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(default=datetime.datetime(2019, 2, 25, 10, 9, 2, 166751, tzinfo=utc), max_length=250)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Article')),
            ],
        ),
        migrations.CreateModel(
            name='QuizLink',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Article')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='UNDEFINED', unique=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Date',
            field=models.CharField(default=datetime.datetime(2019, 2, 25, 10, 9, 2, 164751, tzinfo=utc), max_length=250),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='quizlink',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Quiz'),
        ),
        migrations.AddField(
            model_name='articlelink',
            name='filePath',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.File', to_field='file'),
        ),
    ]
