# Generated by Django 2.1.3 on 2019-02-26 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20190225_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 2, 26, 12, 22, 28, 732342, tzinfo=utc), max_length=250),
        ),
        migrations.AlterField(
            model_name='articlelink',
            name='id',
            field=models.AutoField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Date',
            field=models.CharField(default=datetime.datetime(2019, 2, 26, 12, 22, 28, 730341, tzinfo=utc), max_length=250),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.AutoField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizlink',
            name='id',
            field=models.AutoField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
