# Generated by Django 2.1.3 on 2019-04-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20190410_1219'),
        ('quickstart', '0005_auto_20190410_1028'),
    ]

    operations = [
    ]
