# Generated by Django 2.1.3 on 2019-04-04 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20190401_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Score', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 4, 4, 10, 24, 42, 138661, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 4, 4, 10, 24, 42, 136692, tzinfo=utc), max_length=100),
        ),
        migrations.AddField(
            model_name='articlescore',
            name='ArticleName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Article'),
        ),
    ]
