# Generated by Django 2.1.3 on 2019-04-11 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_merge_20190410_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
