# Generated by Django 2.1.3 on 2019-02-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_auto_20190226_1322'),
        ('quickstart', '0008_auto_20190226_1357'),
    ]

    operations = [
    ]
