# Generated by Django 2.1.3 on 2019-04-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20190411_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiztimer',
            field=models.IntegerField(default=10, max_length=10),
        ),
    ]
