# Generated by Django 2.1.3 on 2019-04-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_quiz_quiztimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiztimer',
            field=models.IntegerField(default=10),
        ),
    ]
